### ISSUE TITLE
Error view in server side is url is not good looking 

### ISSUE THREAD

**Issue by mayursamnani36** [scorelab/LabelLab#208] opened 2020-01-10 20:06 UTC
**Is your feature request related to a problem? Please describe.**

Currently the error.ejs file displays an html page that is just plain text which is not good looking at all.

**Describe the solution you'd like**
I would like to implement material UI design using materialize.css to make it look more cleaner and add an error image so that it looks better.
.
**Screenshot**
![Screenshot from 2020-01-11 01-51-45](https://user-images.githubusercontent.com/54547503/72183887-1d5fda00-3415-11ea-8430-acac082e1ee5.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mayursamnani36** [comment] 2020-01-10 20:06
I am currently working on this now

**Comment by UdeshUK** [comment] 2020-01-10 20:37
@mayursamnani36 it's good to have a better error page. But can we do it without materialize.css to make it not bloated? Also currently, this API is private for the web and mobile clients so appearance is not much of an issue.

**Comment by mayursamnani36** [comment] 2020-01-10 20:44
@UdeshUK Okay i will try to make it look better without using materialize.css. But adding an image is fine though right ?

**Comment by UdeshUK** [comment] 2020-01-10 21:07
> @UdeshUK Okay i will try to make it look better without using materialize.css. But adding an image is fine though right ?

Yes, of course.

**Comment by mayursamnani36** [comment] 2020-01-11 05:39
@UdeshUK Not a problem. I will try to make a error handler but i don't know much about express.js framework. If i am not able to then i will inform you for that as well. Just give me some time. Thank you.

**Comment by mayursamnani36** [comment] 2020-01-12 13:13
@UdeshUK I have to display the error as JSON data on localhost:4000 right ?

**Comment by mayursamnani36** [comment] 2020-01-13 05:32
@UdeshUK please guide me. I am able to display json data on error page. Am i gping right ?

**Comment by UdeshUK** [comment] 2020-01-15 04:38
@mayursamnani36 Yes, it should display a JSON data on the error page. But it has to be formated in the way any other endpoint of server presents an error.

**Comment by UdeshUK** [comment] 2020-01-15 15:03
Same issue #181

**Comment by UdeshUK** [comment] 2020-01-15 15:04
Duplicate of #181

**Comment by carpecodeum** [comment] 2020-01-21 12:58
I would like to work on this and it seems i might have a solution so should I start working on it?

**Closed** 2020-01-23 04:30 UTC
Labels: backend
